### ISSUE TITLE
Provide version 2020.1

### ISSUE THREAD

**Issue by FranklinChen** [dylan-lang/homebrew-dylan#4]
I noticed a new release of OpenDylan has come out: https://opendylan.org/news/2020/10/10/new-release.html

**Comment by housel** [comment]
Yes. As far as I know we don't currently have anyone with enough Homebrew expertise (I use MacPorts); is that something you could try updating?

**Comment by FranklinChen** [comment]
Yes, I've contributed before, and can do it again.
